name: Designing Space to Play In
favicon: null
layout_spectrum: 0.23917
typography_spectrum: 0.3635062803514302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.625
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
